### ISSUE TITLE
Failed Host Check: pihole vs xxx

### ISSUE THREAD

**Issue by nicolinux** [diginc/docker-pi-hole#105]
Hi,

I've deployed the pihole container on my home server. When I try to access `/admin`, I get this error:
`Failed Host Check: pihole vs 192.168.5.201, , , pi.hole, localhost, 192.168.5.201`

Maybe this is due to my "unusual" setup. I already had a reverse proxy in place so I am not using jwilder/proxy. I have the following in my nginx container (which is bound to 80:80) - nginx.conf

```
    server {
        listen 80;
        server_name myserver;
        location /confluence {
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://confluence:8090/confluence;
            client_max_body_size 500M;
        }

        location / {
            proxy_pass http://pihole;
        }
    }
```

On another location I am running Confluence. I have setup the docker-compose for pihole to bind port 8080:80 and apparently this is fine for pihole:
```
  pihole:
    image: diginc/pi-hole
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - ServerIP=192.168.5.201
      - DNS1=192.168.5.1
      - DNS2=8.8.8.8
    ports:
      - "53:53"
      - "8080:80"
```

I bet it is an user error...
Thanks!
