### ISSUE TITLE
Cors errors

### ISSUE THREAD

**Issue by nlamirault** [diginc/docker-pi-hole#121]
Hi
i try to use docker-pihole, i've got an error on the AdminLTE web page :

http://10.33.1.81:9180/admin/

Using the docker-compose.yml file :

```yaml
version: '2'
services:
  pihole:
    image: diginc/pi-hole:alpine_v2.13.2
    container_name: pihole
    environment:
      ServerIP: 10.33.1.81
      DNS1: 8.8.8.8
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9180:80/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
```
```bash
$ docker-compose up
[...]
Status: Downloaded newer image for diginc/pi-hole:alpine_v2.13.2
Recreating pihole ...
Recreating pihole ... done
Attaching to pihole
pihole    |  ::: Starting docker specific setup for docker diginc/pi-hole
pihole    | Assigning random password: 4oaDPGWK
pihole    | New password set
pihole    | Using default DNS servers: 8.8.8.8 & 8.8.4.4
pihole    | DNSMasq binding to default interface: eth0
pihole    | Added ENV to php:
pihole    | [www]
pihole    | env[PATH] = /opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
pihole    | env[PHP_ERROR_LOG] = /var/log/nginx/error.log
pihole    | env[ServerIP] = 10.33.1.81
pihole    | env[VIRTUAL_HOST] = 10.33.1.81
pihole    | Using IPv4 and IPv6
[...]
pihole    | ==> /var/log/nginx/access.log <==
pihole    | 10.33.1.81 - - [27/Apr/2017:07:58:07 +0000] "GET /admin/ HTTP/1.1" 200 378 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
pihole    | 10.33.1.81 - - [27/Apr/2017:07:58:07 +0000] "GET /favicon.ico HTTP/1.1" 200 179 "http://10.33.1.81:9180/admin/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
pihole    |
pihole    | ==> /var/log/nginx/error.log <==
pihole    | 2017-04-27 07:58:07: Failed CORS: evil.com vs 10.33.1.81, , , pi.hole, localhost, 10.33.1.81
pihole    | 2017/04/27 07:58:07 [error] 55#55: *1 open() "/var/www/html/favicon.ico" failed (2: No such file or directory), client: 10.33.1.81, server: , request: "GET /favicon.ico HTTP/1.1", host: "10.33.1.81:9180", referrer: "http://10.33.1.81:9180/admin/"
```
I've go this error :

```
Failed CORS: evil.com vs 10.33.1.81, , , pi.hole, localhost, 10.33.1.81
```

Any idea ? thanks.
