### ISSUE TITLE
Fails to download lists

### ISSUE THREAD

**Issue by respectTheCode** [diginc/docker-pi-hole#145]
I setup pi-hole a few days ago and it was working great but after restarting the container it is unable to download the list. I have removed the container and recreated it several times now but I always get the same thing in the log

```
::: Getting raw.githubusercontent.com list... done
:::   Status: Status 000
:::   Download failed and no cached list available (list will not be considered)
::: Getting mirror1.malwaredomains.com list... done
:::   Status: Status 000
:::   Download failed and no cached list available (list will not be considered)
::: Getting sysctl.org list... done
:::   Status: Status 000
:::   Download failed and no cached list available (list will not be considered)
::: Getting zeustracker.abuse.ch list... done
:::   Status: Status 000
:::   Download failed and no cached list available (list will not be considered)
::: Getting s3.amazonaws.com list... done
:::   Status: Status 000
:::   Download failed and no cached list available (list will not be considered)
::: Getting s3.amazonaws.com list... done
:::   Status: Status 000
:::   Download failed and no cached list available (list will not be considered)
::: Getting hosts-file.net list... done
:::   Status: Status 000
:::   Download failed and no cached list available (list will not be considered)
```

If I connect to the container I can ping addresses that I have added to the hosts file but nothing else and dig always times out.

This is what I have in my docker-compose.yml

```
  pi-hole:
    restart: always
    container_name: pi-hole
    image: diginc/pi-hole
    ports:
      # - 80:80 nginx proxy instead
      - 53:53
      - 53:53/udp
    volumes: 
      - /etc/localtime:/etc/localtime:ro
    environment: 
      ServerIP: 192.168.2.1
      VIRTUAL_HOST: pi-hole.xxxxxxx.com
      WEBPASSWORD: xxxxxxxxxxxx
      DNS1: 192.168.0.1
      DNS2: 192.168.0.1
    extra_hosts:
      - "ha.xxxxxxx.com:192.168.2.1"
      - "portainer.xxxxxxx.com:192.168.2.1"
      - "pi-hole.xxxxxxx.com:192.168.2.1"
```

**Comment by respectTheCode** [comment]
I found the problem and a fix. Once the docker host get the new dns address then the pi-hole container gets it too. The problem is that the network IP of the docker host is not reachable from the container. The fix is to set the dns for the container to something that is reachable.

This isn't a bug in docker-pi-hole but should be documented for new users.

```
  pi-hole:
    restart: always
    container_name: pi-hole
    image: diginc/pi-hole
    dns: 192.168.0.1
    ports:
      # - 80:80 nginx proxy instead
      - 53:53
      - 53:53/udp
    volumes: 
      - /etc/localtime:/etc/localtime:ro
    environment: 
      ServerIP: 192.168.2.1
      VIRTUAL_HOST: pi-hole.xxxxxxx.com
      WEBPASSWORD: xxxxxxxxxxxx
      DNS1: 192.168.0.1
      DNS2: 192.168.0.1
    extra_hosts:
      - "ha.xxxxxxx.com:192.168.2.1"
      - "portainer.xxxxxxx.com:192.168.2.1"
      - "pi-hole.xxxxxxx.com:192.168.2.1"
```
