### ISSUE TITLE
Update Pihole to Version 3.2

### ISSUE THREAD

**Issue by Happyfeet01** [diginc/docker-pi-hole#193]
Hello,.
These days Pihole 3.2 is released.
is it possible to Backup the Stats from pihole with an Variable?

**Comment by diginc** [comment]
Debian is on the dev tag: https://github.com/diginc/docker-pi-hole/pull/191
Alpine is going to take some more work: https://github.com/diginc/docker-pi-hole/pull/192

**Comment by basrieter** [comment]
Will #191 also work for Raspberry Pi's ARM?

**Comment by diginc** [comment]
ARM used to be automated but was refactored to a new base image which broke that automatic building and pushing of it.  https://github.com/diginc/docker-pi-hole/issues/177 is the issue to track re-implmenting that through Travis-CI.

I will get a copy of debian_arm pushed to https://hub.docker.com/r/diginc/pi-hole-multiarch/tags/ a little later today.

**Comment by Happyfeet01** [comment]
Im stucking with docker compose at this point.

```
pihole    | Using IPv4 and IPv6
pihole    | ::: Testing DNSmasq config: dnsmasq: syntax check OK.
pihole    | ::: Testing lighttpd config: Syntax OK
pihole    | ::: All config checks passed, starting ...
pihole    | ::: Docker start setup complete - beginning s6 services
pihole    |   [✗] DNS resolution is currently unavailable
```

**Comment by diginc** [comment]
Try adding --dns 127.0.0.1, that is what I did in the tests

**Comment by Happyfeet01** [comment]
You mean delete the DNS Entrys and add this:

```
version: '2'                                                                                      services:
  pihole:
    container_name: pihole
    restart: always                                                                                   image: diginc/pi-hole:debian_dev
    environment:
    - ServerIP=81.169.210.40
    - ServerIPv6=2a01:238:4246:af00:9e2a:c21f:825:ff1b
    - TZ=Europe/Berlin
    - WEBPASSWORD=lamue80@pihole
    - DNS1=8.8.8.8
    - DNS2=8.8.4.4
    - DNS=127.0.0.1
    - VIRTUAL_HOST=pihole.larsmueller.net
    volumes:
    - /var/pihole/:/etc/pihole/                                                                       - /var/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
    - "8888:80"
    - "53:53/tcp"                                                                                          - "53:53/udp"                                                                                                                   
```

**Comment by diginc** [comment]
Sorry, I meant like this:

```
version: '2'                                                                                      
services:
  pihole:
    container_name: pihole
    restart: always                                                                                   
    image: diginc/pi-hole:debian_dev
    dns:
    - 127.0.0.1
    - 8.8.8.8
    environment:
    - ServerIP=81.169.xxx.xx
    - ServerIPv6=xxx:238:4246:af00:9e2a:c21f:825:ff1b
    - TZ=Europe/Berlin
    - WEBPASSWORD=
    - DNS1=8.8.8.8
    - DNS2=8.8.4.4
    - DNS=127.0.0.1
    - VIRTUAL_HOST=pihole.domain.tld
    volumes:
    - /var/pihole/:/etc/pihole/                                                                       - /var/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
    - "8888:80"
    - "53:53/tcp"  
```
