### ISSUE TITLE
Unable to parse results from queryads.php

### ISSUE THREAD

**Issue by pascalgoty** [diginc/docker-pi-hole#224]
Hi, i've setup a new clean, config free docker pi-hole instance and i'm getting this error message when i open the webpage : [ERROR]: Unable to parse results from queryads.php: Unhandled error message (Invalid domain!)

Anyone knows why i'm getting this ? 

``` 
***LOGS***
setupVars=/etc/pihole/setupVars.conf
 ::: Starting docker specific setup for docker diginc/pi-hole
  [✓] New password set
Using custom DNS servers: 209.222.18.222 & 209.222.18.218
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "192.168.0.2",
			"VIRTUAL_HOST" => "192.168.0.2",
Using IPv4 and IPv6
dnsmasq: syntax check OK.
::: Testing DNSmasq config: ::: Testing lighttpd config: Syntax OK
::: All config checks passed, starting ...
::: Docker start setup complete
  [✗] DNS resolution is currently unavailable
  [✓] DNS resolution is now available

  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: Retrieval successful

  [i] Target: sysctl.org (hosts)
  [✓] Status: Retrieval successful

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: Retrieval successful

  [i] Target: hosts-file.net (ad_servers.txt)
  [✓] Status: Retrieval successful

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] 130093 domains being pulled in by gravity
  [✓] Removing duplicate domains
  [i] 106983 unique domains trapped in the Event Horizon

  [✓] Adding 6 blocklist source domains to the whitelist
  [✓] Whitelisting 0 domains
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

pihole-FTL: no process found
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting pihole-FTL
Starting dnsmasq
Starting crond
Starting lighttpd
[services.d] done.
```

```
Docker-compose.yml

version: "3"
services:
  pihole:
    image: diginc/pi-hole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8053:80/tcp
    dns: 127.0.0.1
    volumes:
      - ./config/pihole:/etc/pihole
      - ./config/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: 192.168.0.2
      TZ: America/Toronto
      DNS1: 209.222.18.222
      DNS2: 209.222.18.218
    restart: always
```

Thanks
