### ISSUE TITLE
"DataTables warning: table id=all-queries" after pulling the latest image

### ISSUE THREAD

**Issue by unixfox** [diginc/docker-pi-hole#225]
I've upgraded my docker-pi-hole to the latest image using:
```
docker-compose stop
docker-compose rm -f
docker-compose pull   
docker-compose up -d
```
When I browse to the "Query log" section I get this error:
```
DataTables warning: table id=all-queries - Requested unknown parameter '5' for row 0, column 5. For more information about this error, please see http://datatables.net/tn/4
```
I tried to increase the limit of php with theses two values: https://github.com/pi-hole/AdminLTE/pull/308/files but that solve nothing.

**Comment by diginc** [comment]
Have you tried moving any existing volume data to the side and starting fresh?

**Comment by unixfox** [comment]
You mean reinstalling and erase my existing volume? If I do that I will lost most of my existing settings (blocklists, whitelist and blacklist). 
By the way I'm forgot to tell you that I'm using the debian_dev branch.

**Comment by diginc** [comment]
You don't need to delete your existing volumes on the off chance it's not the data in them causing the problem.  I'd suggest just moving them to the side and re-creating the container again so it creates an empty volume directory.

**Comment by unixfox** [comment]
I tried but it didn't fix the issue, here is what I did:
```
docker-compose stop
docker-compose rm -f
mv etc etc.back
docker-compose pull
docker-compose up -d
```

**Comment by diginc** [comment]
What does your dockerfile look like?

is your volume `./etc/:/etc/` ?  Try without that.

**Comment by unixfox** [comment]
Here is my `docker-compose.yml`:
```
version: "2"
services:
  pihole:
    image: diginc/pi-hole:debian_dev
    dns:
    - 127.0.0.1
    - 9.9.9.9
    ports:
      #- "53:53/tcp"
      #- "53:53/udp"
      - "8080:80/tcp"
    environment:
      - ServerIP=185.52.3.141
      - VIRTUAL_HOST=pihole.unixfox.eu
      - DNS1=139.59.208.246
      - DNS2=9.9.9.9
      - DNS=127.0.0.1
      - IPv6="False"
      - TZ=Europe/Brussels
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=Cejohtie1puhe
    volumes:
      - '/root/pihole/etc/:/etc/pihole/'
      - '/root/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      dns:
        ipv4_address: 172.23.1.254
        aliases:
          - pihole
    restart: always
  wrapper:
    image: vimagick/dnscrypt-wrapper
    ports:
      - "4443:443/udp"
      - "4443:443/tcp"
    dns:
        - 172.23.1.254
    volumes:
      - '/root/pihole/dnscrypt/:/var/lib/dnscrypt-wrapper'
    environment:
      - LISTEN_ADDR=0.0.0.0:443
      - RESOLVER_ADDR=172.23.1.254:53
      - PROVIDER_NAME=2.dnscrypt-cert.unixfox.eu
    depends_on:
      - pihole
    networks:
      dns:
        aliases:
          - dnscrypt
    restart: always

networks:
  dns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.1.0/24
```
