### ISSUE TITLE
pihole-FTL: no process found

### ISSUE THREAD

**Issue by skalg** [diginc/docker-pi-hole#241]
Im using the latest image and i got pihole-FTL: no process found with a clean config/volume.

Here's the last lines of logs
```

pihole_1  | 
pihole_1  | pihole-FTL: no process found
pihole_1  |   [✓] DNS service is running
pihole_1  |   [✓] Pi-hole blocking is Enabled
pihole_1  | [cont-init.d] 20-start.sh: exited 0.
pihole_1  | [cont-init.d] done.
pihole_1  | [services.d] starting services
pihole_1  | Starting pihole-FTL
pihole_1  | Starting dnsmasq
pihole_1  | Starting crond
pihole_1  | [services.d] done.
pihole_1  | Starting lighttpd
pihole_1  | dnsmasq: started, version 2.76 cachesize 10000

```

And /admin/api.php?overTimeData10mins gives me FTLnotrunning | true

**Comment by diginc** [comment]
Do you have a docker run command to reproduce this problem?

**Comment by pascalgoty** [comment]
Here's my docker-compose, i've also tried with volumes for /etc/pihole and /etc/dnsmasq.d

version: "3"
services:
  pihole:
    image: diginc/pi-hole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    dns: 127.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: 192.168.0.2
      TZ: America/Toronto
      DNS1: 209.222.18.222
      DNS2: 209.222.18.218
      WEBPASSWORD: 1234
    restart: always

**Comment by nickbabcock** [comment]
Same issue. FTL not running so no graphs (pihole itself still works). Also using docker-compose. I was updating from `diginc/pi-hole:debian_v3.2.1`. Pihole was also pegged at 100% CPU usage for some reason.

```yaml
version: '3'
services:
  pihole:
    container_name: 'pihole'
    image: 'diginc/pi-hole:debian_v3.3'
    restart: 'unless-stopped'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8182:80'

    # For me this env file needs ot have WEBPASSWORD, ServerIP, VIRTUAL_HOST
    env_file: pihole-variables.env
    environment:
      IPv6: 'False'
    volumes:
      - '/tank/containers/pihole/etc:/etc/pihole/'
      - '/tank/logs/pihole.log:/var/log/pihole.log'
```

Rolling back to `diginc/pi-hole:debian_v3.2.1` worked fine.
