### ISSUE TITLE
lighttp.conf error on line 38

### ISSUE THREAD

**Issue by AdriVillaB** [diginc/docker-pi-hole#247]
This is a... 

- [ ] Request for a new or modified feature
- [x ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

After updating to the last version of the image, the lighttpd.conf file have some error on that throws syntax errors. The line which has the error is the 38, related with the server socket.

## Actual Behavior

This error is logged on the logfile:
`2018-03-20 17:30:15: (configfile.c.1154) source: /etc/lighttpd/lighttpd.conf line: 39 pos: 1 parser failed somehow near here: 53`

The configuration file looks like this on the affected lines:
```
29 server.document-root        = "/var/www/html"
30 server.error-handler-404    = "pihole/index.php"
31 server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
32 server.errorlog             = "/var/log/lighttpd/error.log"
33 server.pid-file             = "/var/run/lighttpd.pid"
34 server.username             = "www-data"
35 server.groupname            = "www-data"
36 server.bind              = "10.66.0.60"
37 server.port              = 80
38 $SERVER["socket"] == "127.0.0.1:80" {}53
39 accesslog.filename          = "/var/log/lighttpd/access.log"
40 accesslog.format            = "%{%s}t|%V|%r|%s|%b"
41 
42 index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
43 url.access-deny             = ( "~", ".inc", ".md", ".yml", ".ini" )
44 static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
```

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. 
2. 
3. 
4. 

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Fedora 26
* Docker Version: Docker version 18.02.0-ce, build fc4de44
* Image ID: sha256:ad8aa343febfce673fef6ed81f15d8adf7d00fab1cb03057c986ea7d7a1d8281
* Image: diginc/pi-hole:debian

**Comment by diginc** [comment]
Can you provide your docker run command?

I've tested the two conditions that I spotted modified lighttpd.conf during container startup, --net=host and -E WEB_PORT=<number> but wasn't able to reproduce this: `docker rm pihole; docker run -it --name pihole -e ServerIP=0.0.0.0 -e WEB_PORT=9999 -e PH_VERBOSE=1 --net=host diginc/pi-hole:latest bash`

**Comment by AdriVillaB** [comment]
I'm using docker-compose with this config file:

```
version: '2'
services:
  pihole:
    image: diginc/pi-hole:debian
    container_name: pihole
    restart: 'always'
    network_mode: 'host'
    volumes:
      - '/media/pihole/pihole/:/etc/pihole/'
      - '/media/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    environment:
      - DNSMASQ_LISTENING=all
      - INTERFACE=enp3s0
      - ServerIP=10.66.0.60
      - PROXY_LOCATION=pihole
      - TZ=Europe/Madrid
      - DNS1=8.8.8.8
      - DNS2=8.8.4.4
      - WEBPASSWORD=XXXXXXXXXXXX
      - WEB_PORT=8053
    extra_hosts:
      - 'pihole pihole.adrivillab.local:10.66.0.60'

```
