### ISSUE TITLE
Getting "ERROR: ServerIP Environment variable ("192.168.5.50") doesn't appear to be a valid IPv4 address" only with latest container image

### ISSUE THREAD

**Issue by toasterlint** [diginc/docker-pi-hole#297]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Previously running :latest fine for several months with the same config (ENV variables, data volumes, etc).  Watchtower updated image last night and now container is continually restarting

## Expected Behavior

Container should run as it previously did

## Actual Behavior

Docker logs reports the following:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific setup for docker diginc/pi-hole
ERROR: ServerIP Environment variable ("192.168.5.50") doesn't appear to be a valid IPv4 address
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

## Possible Fix

Unknown.  Temporary work-around is to no longer run :latest and now run :debian_v3.3 which is working completely fine.

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

I attempted to use fresh new data volumes with :latest label as well and it still failed.  Only running the :debian_v3.3 image is working at all

When I manually run (via docker exec) the nc and ip route commands found on line 21 of the bash_functions.sh within the container for the very brief few seconds the container is up both commands execute without issue and report back as expected (netcat's results are empty and ip route exit code 0)

## Your Environment 

* Docker Host Operating System and OS Version: Arch Linux
* Docker Version: 18.05.0-ce
* Hardware architecture: amd64

Also, I use Docker Compose to run my environment (single host, not part of swarm).  The following is my config for pihole in case it helps (password removed).  Again, running debian_v3.3 works, changing back to latest causes error and continual restart:

```
pihole:
    image: diginc/pi-hole:debian_v3.3
    restart: always
    networks:
      pub_net:
        ipv4_address: 192.168.5.50
    hostname: pihole
    environment:
      - ServerIP="192.168.5.50"
      - DNS1="8.8.8.8"
      - DNS2="8.8.4.4"
      - WEBPASSWORD="blahblah"
    volumes:
      - /data/Docker/pihole/pihole:/etc/pihole/
      - /data/Docker/pihole/dnsmasq.d:/etc/dnsmasq.d/
```
